services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  code-engine:
    build:
      context: .
      dockerfile: Dockerfile
    image: code-engine
    container_name: code-engine-server
    restart: on-failure
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["./code-engine"]
